/**
 * 事件处理状态
 * @type {{A: string, B1: string, B2: string, B3: string, B4: string, B5: string, E1: string, E2: string, E3: string, E4: string, E5: string, H1: string, H2: string, H3: string, H4: string, H5: string, G1: string, G2: string, G3: string, G4: string, G5: string, K1: string, K2: string, K3: string, K4: string, K5: string, M1: string, M2: string, M3: string, M4: string, N1: string, N2: string, N3: string, N4: string, N5: string, F: string, Z1: string, Z2: string, Z3: string, Z4: string, Z5: string, B: string, C: string, D: string, E: string, G: string, H: string, I: string, Z: string, X: string, T: string, J1: string, J2: string, J3: string, J4: string, J5: string, L1: string, L2: string, L3: string, L4: string, L5: string}}
 */
export const eventStatusEnum={
  A: "问题上报",
  B1: "省级联络员派单",
  B2: "市级联络员派单",
  B3: "区级联络员派单",
  B4: "街级联络员派单",
  B5: "村级联络员派单",
  E1: "省级河长派单 ",
  E2: "市级河长派单",
  E3: "区级河长派单",
  E4: "街级河长派单",
  E5: "村级河长派单",
  H1: "省级河长确认",
  H2: "市级河长确认",
  H3: "区级河长确认",
  H4: "街级河长确认",
  H5: "村级河长确认",
  G1: "省级联络员反馈求助",
  G2: "市级联络员反馈求助",
  G3: "区级联络员反馈求助",
  G4: "街级联络员反馈求助",
  G5: "工作人员反馈求助",
  K1: "省级河长反馈求助",
  K2: "市级河长反馈求助",
  K3: "区级河长反馈求助",
  K4: "街级河长反馈求助",
  K5: "工作人员反馈求助",
  M1: "省级河长助理结案",
  M2: "市级河长助理结案",
  M3: "区级河长助理结案",
  M4: "街级河长助理结案",
  N1: "省级委办局处理",
  N2: "市级委办局处理",
  N3: "区级委办局处理",
  N4: "街级委办局处理",
  N5: "村级委办局处理",
  F: "工作人员处理",
  Z1: "省级河长确认结案",
  Z2: "市级河长确认结案",
  Z3: "区级河长确认结案",
  Z4: "街级河长确认结案",
  Z5: "村级河长确认结案",
  B: "受理",
  C: "核实",
  D: "确认",
  E: "派单",
  G: "已处理",
  H: "审核",
  I: "结案",
  Z: "已结案",
  X: "无效问题",
  T: "事务锁定",
  J1: "省级河长办审核",
  J2: "市级河长办审核",
  J3: "区级河长办审核",
  J4: "街级河长办审核",
  J5: "村级河长办审核",
  L1: "省级河长办处理",
  L2: "市级河长办处理",
  L3: "区级河长办处理",
  L4: "街级河长办处理",
  L5: "村级河长办处理",
};
